### ISSUE TITLE
This API doesn't quite work

### ISSUE THREAD

**Issue by gaearon** [Swizec/useDimensions#3] opened 2019-03-14 00:49 UTC
I think this API only works in simple cases. My hunch is it won't work for something like:

```js
const MyComponent = () => {
  const [ref, { x, y, width }] = useDimensions();
  return <Parent childRef={ref} />;
};

const Parent = ({ childRef }) => {
  const [showChild, setShowChild] = useState(false)
  return (
    <>
      <div ref={childRef}>Hello</div>
      <button onClick={() => setShowChild(!showChild)}>Toggle</button>
    </>
  )
}
```

The reason it won't work is because parent's layout effect won't be notified if something in the child is mounted and unmounted. So I think trying to `useLayoutEffect` to "react" to ref changes is the wrong approach.

Instead, the way you "react" to ref changes in React is with a ref callback. Such as

```js
<div ref={node => {
  // this gets called regardless of how deep it's mounted/unmounted,
  // and you can use it for measurements if you want
}} />
```

**Comment by Swizec** [comment] 2019-03-14 15:01
Hm I didn't think of that. My use case when developing was to statically measure size on initial mount and I didn't need those dimensions to update.

So it made sense to "react" to the initial setting of the ref and stop there. This is a better approach though you're right

**Comment by k15a** [comment] 2019-03-18 16:43
@gaearon Can you please elaborate on how a callback ref would work when we would use ResizeObserver to listen to updates of the dimensions?

The problem I see here is that every time we call setState we would have a new callback ref. React would call the old callback ref with null and the new one with the new DOM node. At this time we would measure the DOM and call setState again which would trigger another rerender and we are in an infinite loop. We could, of course, shallow compare the previous dimensions and new dimensions and only trigger a set state when the dimensions changes but the general problem is still there.

Another solution is to use `useCallback` to memorize the callback ref which wouldn't change between renders anymore. The problem is that this will break as soon as we need to read some values from props or state in the callback.

After reading the documentation I thought that the right place to measure something in the DOM is `useLayoutEffect`. Apparently, this is not always the case as you described above.

It seems that this is a common misunderstanding as you can see [here](https://github.com/ZeeCoder/use-resize-observer/blob/master/src/index.js#L9) and [here](https://github.com/rehooks/component-size/blob/master/index.js#L32).

Would be nice if you could write a small example of how this would be solved correctly. Maybe this is even something for the FAQ.

**Comment by gaearon** [comment] 2019-03-18 17:12
>Another solution is to use useCallback to memorize the callback ref which wouldn't change between renders anymore. The problem is that this will break as soon as we need to read some values from props or state in the callback.

Can you please provide an example for why you'd want to read props or state in the ref callback when measuring nodes?

**Comment by k15a** [comment] 2019-03-18 17:57
Not for measuring specifically but one use case would be as options for the [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) or [Popper.js](https://popper.js.org/). Probably the solution is similar to the solution of the [`useInterval`](https://overreacted.io/making-setinterval-declarative-with-react-hooks/) from you.

**Comment by gaearon** [comment] 2019-03-18 18:02
I'd appreciate a CodeSandbox demonstrating the issue. Then I can help find a solution.

**Comment by k15a** [comment] 2019-03-18 18:55
Sure I've created two demos here:
- [IntersectionObserver](https://codesandbox.io/s/o587j5x0nz)
- [Popper.js](https://codesandbox.io/s/wwk77nn2l7)

**Comment by gaearon** [comment] 2019-03-19 17:44
Btw I added the measurement use case to FAQ.
https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node

**Comment by gaearon** [comment] 2019-03-19 17:55
@k15a I don't think your examples include an explanation of which props you're using and why. Can you please imagine that I'm new to these APIs and walk me through the problem with the solution I proposed earlier. Thanks.

**Comment by gaearon** [comment] 2019-03-19 17:56
In particular the first example doesn't seem to use any props or state during the ref callback. Maybe I'm missing something.

**Comment by k15a** [comment] 2019-03-20 13:35
Sorry, I thought a little bit to complicated and everything works really nicely. Especially because I can update the callback ref every time I have an updated config and React will handle the rest afterwards. I've created an [example here](https://codesandbox.io/s/kqoo33m23).

One last question: Did you consider an API like this for callback at the time when you added them to React and if you did what speaks against it? 

```js
function Component() {
  function ref(node) {
    // This would work exactly like callback refs currently work

    return function cleanup() {
      // This function would be called instead of ref(null)
    };
  }

  return <div ref={ref} />;
}
```

Thank you very much for the help 🙏

**Comment by jacobp100** [comment] 2019-03-20 17:49
Just a note, I've opened an issue in React for this [here](https://github.com/facebook/react/issues/15167)

**Comment by Swizec** [comment] 2019-03-21 04:28
Implementation has been fixed to rely on `useCallback`. Thanks for the help @gaearon.

Closing this for now.

**Closed by Swizec** 2019-03-21 04:28 UTC
